### ISSUE TITLE
Support for Spring Cloud

### ISSUE THREAD

**Issue by johnyannj** [googleapis/java-servicedirectory#578]
can servicedirectory be used for Spring Cloud's  Service Registry Discovery？

**Comment by Neenu1995** [comment]
Reducing priority while waiting for reply.

**Comment by suztomo** [comment]
It’s preview status and available in “com.google.cloud:google-cloud-servicedirectory-spring-starter”

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-previews/README.md
